### PR TITLE
Development

### PR DESCRIPTION
**Pull request by bhushankumarl**

### CODE REVIEW

**Comment by bhushankumarl** [comment]
@beastmike1 @wangjue666 @sottenad
Your PR is merged here. Can you please validate once so I can release a new version?

**Comment by bhushankumarl** [comment]
@tylerreece22 
Can you confirm, after merge all features working perfectly?

@beastmike1 @wangjue666 @sottenad
Can you please validate once so I can release a new version?

Your inputs will highly appreciated.

**Comment by tylerreece22** [comment]
@bhushankumarl I can check submitFeed, feedResult, and resultList. Those are really the only ones I am familiar with for my project.

**Comment by tylerreece22** [comment]
@bhushankumarl submitFeed, feedResult, and resultList all work as expected with my change.

**Comment by jesusvalle** [comment]
@bhushankumarl  @beastmike1 Hi, I have tested the STREAM function with a big data file of orders and listings reports and it works perfectly.

I would recommend to add to the documentation something to make people use that method from the beginning so they don't have to remake all their code as it happened to us.

**Comment by tylerreece22** [comment]
@bhushankumarl can we get this PR merged? I would prefer to use this library for my project but without the bug fix I provided this module wont work.

**Comment by beastmike1** [comment]
@bhushankumarl Hi I have have tested the STREAM fucntion and all is working fine

**Comment by tylerreece22** [comment]
@bhushankumarl it seems the code has been tested. Can you please merge?

**Comment by sottenad** [comment]
@bhushankumarl - I have tested/reviewed the development branch after these PR's and my change is looking fine! +1 to merge to master.

**Comment by tylerreece22** [comment]
Cricket cricket 🦗

**Comment by bhushankumarl** [comment]
@tylerreece22 @jesusvalle @beastmike1 @sottenad Thank you all. 
The new version has been released.
https://github.com/bhushankumarl/amazon-mws/releases/tag/v0.0.25
https://www.npmjs.com/package/amazon-mws

**Comment by tylerreece22** [comment]
@bhushankumarl yay! thanks!

**Pull request merged**
