### PR TITLE
Merge request from my development branch to your development branch

### PR DESCRIPTION
**Pull request by markspeich**
I changed the 'let' modifier to 'var', as you requested. I also closed the old pull request and opened a new one going from my 'development' branch to your 'development' branch. 

I didn't make a deep copy of the requestParametersJSON and send it into 'makeRequest' as a parameter since, as far as I can tell, that variable isn't used inside the 'makeRequest' callback. If you think I'm mistaken, let me know.

### CODE REVIEW

**Comment by markspeich** [comment]
There is an accidental commit for merging master into development. Please hold off on approving this and I'll fix when I get a chance tomorrow.

**Comment by bhushankumarl** [comment]
@markspeich 
That variable is used here in the response handler at Line No 222. 
So. we should make sure that response to each request should also not override/duplicate.

**Comment by markspeich** [comment]
@bhushankumarl 
I fixed the accidental merge in my development branch, and added a new commit that makes a deep copy of the requestParamsJSON and passes that to the _responseHandler method. Take a look and let me know if this is what you had in mind.

**Comment by bhushankumarl** [comment]
@markspeich New version has been released with this changes.
https://github.com/bhushankumarl/amazon-mws/releases/tag/v0.0.14
Kindly install it and let me if it does work for you or not.
Thank you @markspeich

**Comment by markspeich** [comment]
@bhushankumarl Just tried it out, and it seems to be working fine! Thanks.

**Pull request merged**
