### PR TITLE
Fixes #104 - A way to handle big results of requests

### LINKED ISSUE #104: Huge Reports Issue
Hi, we are having troubles processing some reports from sellers with a huge catalogue, like 600k products for each marketplace. 

For example, an open listing report from one of that sellers after been parsed for your library and saved to a txt file, it weighs more than 200 mb.

I think that a way to pipe the report result directly to a file it could be better than caching all the response in a variable in that cases, would that be possible? 

Thanks.

### PR DESCRIPTION
**Pull request by beastmike1**
Added __STREAM__ pseudo-argument to expose the request so it can be handled as a stream

### CODE REVIEW

**Comment by carantes** [comment]
Hey Guys, how are you? I'm facing the same problem using this lib and would be nice to use STREAM to handle big requests. What are the next steps to this PR? Can I help with something?

**Comment by carantes** [comment]
> Hi @carantes It seems that there is no much activity in this repository, if you want you can use my branch until they merge it, if you have any question or suggestion I will be happy to help.

After switch to your branch I started to facing this error:

`Module build failed: Error: ENOENT: no such file or directory, open '/Users/carloseduardoarantesferreira/Workspace/code/fl-mws-importer/node_modules/xml2js/node_modules/xmlbuilder/lib/index.js
`

Thanks for the help beastmike!

**Comment by carantes** [comment]
> Hi @carantes It seems that there is no much activity in this repository, if you want you can use my branch until they merge it, if you have any question or suggestion I will be happy to help.

Hello @beastmike1 ,

After stucked a couple times because my code is all typescript and also I'm using async/await, everything is working now! Processed 2.7MM of rows.

Thanks a lot for your help!   

```
const rawStream = await mws.reports.search({
      Version: MWSAPIVersion.V20090101,
      Action: ReportAction.GetReport,
      SellerId: mwsAuth.accountId,
      MWSAuthToken: mwsAuth.authToken,
      ReportId: reportId,
      __STREAM__: true,
    });

const csvStream = csv.parse({
      delimiter: '\t',
      headers: true,
      discardUnmappedColumns: true,
      ignoreEmpty: true,
      trim: true
});

return new Promise((resolve, reject) => {
      const chunks: any[] = [];
      let chunkCount = 0;
      rawStream
        .pipe(iconv.decodeStream('ISO-8859-1'))
        .pipe(csvStream)
        .on('data', (data: any) => {
          console.log(`[${chunkCount}] data: ${JSON.stringify(data)}`);
          chunks.push(data);
          chunkCount ++;
        })
        .on('end', () => resolve(chunks))
        .on('error', reject);
});
```

**Comment by beastmike1** [comment]
Hi @carantes, I also have all my aplication in Typescript, as I see in your example, You proccess all the data at the end, when you do the resolve, i recommend you to do it in batches or if you encounter a bigger report or if you start doing it with several reports at a time your server will run out of memory, since you are storing all the data in memory before processing it.

For example what i do is to use the transform function of the csvStram to process it line by line

```
function getReport(itemsStream) {
    let rows = new Array();
    let productsCount = 0;
    async function processRow(row, end = false) {
        if (row) {
            productsCount++;
            rows.push(row);
        }
        if (rows.length >= 5000 || (end && rows.length)) {
            sendRowsToDB(rows);
            rows = new Array();
        }
    }
    return new Promise<number>((resolve, reject) => {
        const decodeStream = iconv.decodeStream('ISO-8859-1');
        itemsStream.pipe(decodeStream);
        const csvStream = fast_csv.parse({
            delimiter: '\t',
            headers: true,
            discardUnmappedColumns: true,
            quote: '',
            ignoreEmpty: true,
            trim: true
        });

        decodeStream.pipe(csvStream);

        const transform = (
            data: any,
            cb: (error: any, next?: any) => void
        ): void => {
            processRow(data)
                .then(cb)
                .catch(cb);
        };
        csvStream.transform(transform);
        csvStream
            .on('error', err => {
                console.error(err);
                throw { err };
            })
            .on('finish', async () => {
                await processRow(undefined, true).catch(err => {
                    reject({
                        err,
                        message: 'error processing rows in batches'
                    });
                });
                return resolve(productsCount);
            });
    });
}
```

**Comment by bhushankumarl** [comment]
@beastmike1 @carantes @raymatos 
Can you resolve conflicts?
Please make sure for below things :
- It should pass all the lint warnings/errors.
- It should pass all test cases.

**Comment by beastmike1** [comment]
@bhushankumarl All linting and tests passed

**Pull request merged**
